import Head from 'next/head';

export default function Home() {
  return (
    <div className="p-2">
      <Head>
        <title>Comfort - Make Your Interior More Minimalistic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-5xl font-bold">Besmillah</h1>
      </div>
    </div>
  )
}
