import React from 'react';
import Head from 'next/head';

// Components
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div className="p-3">
      <Head>
        <title>Comfort - Make Your Interior More Minimalistic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl m-auto">
        <Navbar />
        <Hero />
      </div>
    </div>
  )
}
